# Generated by Django 5.1.6 on 2025-02-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_user_is_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenModel',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
